#!/bin/bash

source env/bin/activate

./update_repos.py

export ARCHIVE=$HOME/archive
export DOWNLOADS=$HOME/Downloads
export ISOS=$HOME/isos
export PRIVATEHTML=$HOME/private_html
export SCRATCH=$HOME/scratch
export SYNCEDSNAPSHOTS=$HOME/Sync-snapshots

./chores.py $*
