#!/bin/bash

export STOP_NOTICEBOARD_FILE=/tmp/stop-noticeboard

source noticeboard.env/bin/activate
while [ ! -f $STOP_NOTICEBOARD_FILE ]
do
    ./noticeboard.py $*
done
rm -f $STOP_NOTICEBOARD_FILE
